# Generated by Django 3.1 on 2021-05-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomApp', '0006_auto_20210505_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='phone',
            field=models.CharField(max_length=150),
        ),
    ]
