# Generated by Django 3.1 on 2021-05-07 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_auto_20210507_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='full_name',
        ),
    ]
