# Generated by Django 3.1 on 2021-05-07 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_userprofile_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='full_name',
        ),
    ]
