# Generated by Django 3.1 on 2021-05-15 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderApp', '0002_auto_20210515_1359'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillingAddress',
        ),
    ]
